import { Link } from 'wouter';
import { ArrowRight, Check, Clock3, ExternalLink, FileText, Users, WifiOff } from 'lucide-react';
import { PageFrame, SiteLayout } from '@/components/SiteLayout';
import { applications, announcements, boardMembers, departments, roleplayTypes, siteSettings } from '@/lib/siteData';

export function Home() {
  return <SiteLayout><section className="reference-hero">
    <div className="reference-hero-copy">
      <div className="reference-kicker">1980'S ORIENTED ERLC COMMUNITY</div>
      <h1>Springfield<br /><em>1980's</em><strong>Roleplay</strong></h1>
      <div className="reference-actions"><Link href="/status" className="reference-button reference-button-primary">SESSION STATUS</Link><Link href="/about" className="reference-button reference-button-outline">ABOUT US</Link></div>
    </div>
    <div className="reference-hero-media"><img src="/springfield-blue-scene.webp" alt="Blue Springfield police car and deputy in a Roblox ERLC scene" /><span>1980's oriented server</span></div>
  </section>
  <section className="reference-about"><div className="reference-about-heading"><span>01</span><h2>ABOUT US</h2></div><div className="reference-about-copy"><p>We're a 1980's oriented ERLC roleplay server built for players who want organized sessions, clear departments, and room to make their own scenes.</p><p>Pick a department, join the next session, or play a civilian with your own plan. Springfield is here when you want something easy to get into.</p><Link href="/roleplay" className="reference-text-link">SEE WHAT YOU CAN PLAY <ArrowRight size={15} /></Link></div></section>
  <section className="reference-cards"><article><span>02</span><h2>SESSION STATUS</h2><p>Check the current server connection before you join.</p><Link href="/status" className="reference-text-link">CHECK THE SERVER <ArrowRight size={15} /></Link></article><article><span>03</span><h2>DEPARTMENTS</h2><p>Police, sheriff, fire, rescue, and civilian roles give each session somewhere to go.</p><Link href="/departments" className="reference-text-link">VIEW DEPARTMENTS <ArrowRight size={15} /></Link></article><article><span>04</span><h2>JOIN SPRINGFIELD</h2><p>Read the rules, choose a role, and apply when you know what you want to play.</p><Link href="/applications" className="reference-text-link">START HERE <ArrowRight size={15} /></Link></article></section>
  </SiteLayout>;
}

export function About() { return <PageFrame kicker="ABOUT SPRINGFIELD · 01" title="A place to play" intro="Springfield 1980 is a Roblox ERLC community for regular sessions, clear roles, and easy-to-follow departments."><div className="record-layout"><div className="record-main"><img className="record-image" src="/high-rock-park.webp" alt="High Rock Park entrance in the Roblox ERLC setting" /><h2>Play it your way.</h2><p>Join police, fire, EMS, county services, a business, or a civilian scene. You can stay in one role or try something new on the next session.</p><p>The setting looks like the 1980s, but the sessions are built around the people who join them. Bring a plan, give others room, and make a scene worth coming back to.</p></div><aside className="record-aside"><div className="aside-label">AT A GLANCE</div><div className="glance-number">{siteSettings.members}</div><div className="glance-label">COMMUNITY MEMBERS</div><div className="aside-rule" /><div className="glance-row"><span>SETTING</span><strong>Springfield County</strong></div><div className="glance-row"><span>ERA</span><strong>1980</strong></div><div className="glance-row"><span>PLATFORM</span><strong>Roblox ERLC</strong></div></aside></div></PageFrame>; }

export function Roleplay() { return <PageFrame kicker="ROLEPLAY OPTIONS · 02" title="Choose your role" intro="Pick something you will enjoy, learn the basics, and give the people around you something to respond to."><div className="division-list">{roleplayTypes.map((r) => <article className="division-row" key={r.number}><div className="division-number">{r.number}</div><div className="division-body"><h2>{r.title}</h2><p>{r.text}</p><span>{r.note}</span></div><ArrowRight size={18} /></article>)}</div></PageFrame>; }

export function Departments() { return <PageFrame kicker="DEPARTMENTS · 03" title="Find your department" intro="Every department has a different pace. Read the short version, then check the current application status."><div className="directory-photo-strip"><img src="/park-ranger-vehicles.webp" alt="Roblox ERLC park ranger vehicles in Springfield County" /><img src="/night-police.webp" alt="Roblox ERLC nighttime police response in Springfield" /></div><div className="department-list">{departments.map((d) => <article className="department-record" key={d.name}><div className={`department-record-emblem ${d.color}`}>{d.emblem}</div><div className="department-record-main"><div className="record-code">DEPARTMENT · {d.short}</div><h2>{d.name}</h2><p>{d.description}</p><div className="record-columns"><div><span>LEADERSHIP</span><strong>{d.leadership}</strong></div><div><span>DUTIES</span><strong>{d.duties.join(' · ')}</strong></div><div><span>POSITIONS</span><strong>{d.positions}</strong></div></div></div><div className="recruitment"><span className={`status-chip ${d.recruitment.includes('Accepting') ? 'open' : ''}`}><span />{d.recruitment}</span><a href={d.application} className="text-link">APPLICATION <ArrowRight size={13} /></a></div></article>)}</div></PageFrame>; }

export function Ownership() { return <PageFrame kicker="THE TEAM · 04" title="Who runs Springfield" intro="The staff team organizes sessions, helps members, and keeps the community moving behind the scenes."><div className="board-header"><div>SPRINGFIELD STAFF</div><div>COMMUNITY OPERATIONS</div><div>1980 ROLEPLAY</div></div><div className="board-list">{boardMembers.map((m, i) => <article className="board-row" key={m.name}><div className="board-index">0{i + 1}</div><div className="board-seal">♛</div><div className="board-person"><h2>{m.name}</h2><div className="board-position">{m.position}</div></div><div className="board-area"><span>AREA</span><strong>{m.area}</strong></div><p>{m.bio}</p></article>)}</div></PageFrame>; }

export function Applications() { return <PageFrame kicker="JOIN A DEPARTMENT · 05" title="Start here" intro="Choose a department, read the requirements, and apply through Discord. Staff will explain the next step."><div className="application-list">{applications.map((a) => <article className="application-row" key={a.department}><div className="application-icon"><FileText size={19} /></div><div className="application-body"><div className="record-code">{a.department}</div><h2>{a.position}</h2><p>{a.requirements}</p></div><div className="application-action"><span className={`status-chip ${a.status === 'Open' ? 'open' : ''}`}><span />{a.status}</span><a href="https://discord.com" target="_blank" rel="noreferrer" className="button button-small">APPLY <ExternalLink size={13} /></a></div></article>)}</div></PageFrame>; }

export function Status() { return <PageFrame kicker="SESSION STATUS · 06" title="Check before you join" intro="The live server connection is not set up yet, so this page does not show a made-up player count."><div className="status-panel"><div className="status-panel-top"><div><div className="eyebrow">RIGHT NOW</div><h2>Live check not connected</h2></div><WifiOff size={28} /></div><div className="status-grid"><div><span>EXPERIENCE</span><strong>Roblox ERLC</strong></div><div><span>AVAILABILITY</span><strong className="status-muted">Waiting for the status feed</strong></div><div><span>PLAYER COUNT</span><strong className="status-muted">Not available</strong></div><div><span>LAST UPDATED</span><strong>Not connected yet</strong></div></div><p className="status-note"><Clock3 size={14} /> Connect an official status endpoint here when one is available.</p></div><div className="status-note-box"><Users size={18} /><p>Everything else is open. Read the rules, view departments, or join Discord to ask about the next session.</p><Link href="/about" className="text-link">ABOUT THE COMMUNITY <ArrowRight size={13} /></Link></div></PageFrame>; }

export function Rules() { return <PageFrame kicker="HOUSE RULES · 07" title="Keep it fun" intro="Respect the people in the session, follow your department, and do not ruin somebody else's scene."><div className="rules-list">{['Do not harass or target other members.', 'Follow department procedures during a shift.', 'Keep the 1980s setting in mind.', 'Communicate and let other players have their turn.'].map((rule, i) => <div className="rule-row" key={rule}><span>0{i + 1}</span><p>{rule}</p><Check size={16} /></div>)}</div></PageFrame>; }
