// County Record Office style: page-level civic records with reusable data-driven entries for the Roblox ERLC community.
import { Link } from 'wouter';
import { ArrowRight, Check, Clock3, ExternalLink, FileText, Users, WifiOff } from 'lucide-react';
import { PageFrame, SiteLayout } from '@/components/SiteLayout';
import { applications, announcements, boardMembers, departments, roleplayTypes, siteSettings } from '@/lib/siteData';

export function Home() {
  return <SiteLayout><section className="reference-hero">
    <div className="reference-hero-copy">
      <div className="reference-kicker">1980'S ORIENTED ERLC COMMUNITY</div>
      <h1>Springfield<br /><em>1980's</em><strong>Roleplay</strong></h1>
      <div className="reference-actions"><Link href="/status" className="reference-button reference-button-primary">SESSION STATUS</Link><Link href="/about" className="reference-button reference-button-outline">ABOUT US</Link></div>
    </div>
    <div className="reference-hero-media"><img src="/springfield-blue-scene.webp" alt="Blue Springfield police car and deputy in a Roblox ERLC scene" /><span>1980's oriented server</span></div>
  </section>
  <section className="reference-about"><div className="reference-about-heading"><span>01</span><h2>ABOUT US</h2></div><div className="reference-about-copy"><p>We're a 1980's oriented ERLC roleplay server built for players who want organized sessions, clear departments, and room to make their own scenes.</p><p>Pick a department, join the next session, or play a civilian with your own plan. Springfield is here when you want something easy to get into.</p><Link href="/roleplay" className="reference-text-link">SEE WHAT YOU CAN PLAY <ArrowRight size={15} /></Link></div></section>
  <section className="reference-cards"><article><span>02</span><h2>SESSION STATUS</h2><p>Check the current server connection and find out what is happening before you join.</p><Link href="/status" className="reference-text-link">CHECK THE SERVER <ArrowRight size={15} /></Link></article><article><span>03</span><h2>DEPARTMENTS</h2><p>Police, sheriff, fire, rescue, and civilian roles give every session somewhere to go.</p><Link href="/departments" className="reference-text-link">VIEW DEPARTMENTS <ArrowRight size={15} /></Link></article><article><span>04</span><h2>JOIN SPRINGFIELD</h2><p>Read the rules, look through the roles, and apply when you know what you want to play.</p><Link href="/applications" className="reference-text-link">START HERE <ArrowRight size={15} /></Link></article></section>
  </SiteLayout>;
}

export function About() { return <PageFrame kicker="PUBLIC INFORMATION · 01" title="What Springfield RP is" intro="A Roblox ERLC community set in an imagined 1980s county. We use departments and regular sessions to give people a starting point, not a script they have to follow."><div className="record-layout"><div className="record-main"><img className="record-image" src="/high-rock-park.webp" alt="High Rock Park entrance in the Roblox ERLC setting" /><h2>A community built around regular sessions.</h2><p>Springfield has police, fire, EMS, county services, businesses, and civilian roleplay in the same place. You can join a department, make your own civilian story, or switch between both when you feel like trying something different.</p><p>The setting uses the look of an early-1980s American county, but the important part is how people play together. Staff keep the rules understandable, departments have jobs to do, and members are expected to give other people room in a scene.</p></div><aside className="record-aside"><div className="aside-label">AT A GLANCE</div><div className="glance-number">{siteSettings.members}</div><div className="glance-label">COMMUNITY MEMBERS</div><div className="aside-rule" /><div className="glance-row"><span>SETTING</span><strong>Springfield County</strong></div><div className="glance-row"><span>ERA</span><strong>1980</strong></div><div className="glance-row"><span>PLATFORM</span><strong>Roblox ERLC</strong></div></aside></div></PageFrame>; }

export function Roleplay() { return <PageFrame kicker="ROLEPLAY OPTIONS · 02" title="Choose what you want to play" intro="There is no required uniform here. Pick something you will enjoy, learn the basics, and give the people around you something to respond to."><div className="division-list">{roleplayTypes.map((r) => <article className="division-row" key={r.number}><div className="division-number">{r.number}</div><div className="division-body"><h2>{r.title}</h2><p>{r.text}</p><span>{r.note}</span></div><ArrowRight size={18} /></article>)}</div></PageFrame>; }

export function Departments() { return <PageFrame kicker="DEPARTMENTS · 03" title="The departments" intro="Each department has a different job and a different pace. Read through them before applying so you know what you are signing up for."><div className="directory-photo-strip"><img src="/park-ranger-vehicles.webp" alt="Roblox ERLC park ranger vehicles in Springfield County" /><img src="/night-police.webp" alt="Roblox ERLC nighttime police response in Springfield" /></div><div className="department-list">{departments.map((d) => <article className="department-record" key={d.name}><div className={`department-record-emblem ${d.color}`}>{d.emblem}</div><div className="department-record-main"><div className="record-code">DEPARTMENT RECORD · {d.short}</div><h2>{d.name}</h2><p>{d.description}</p><div className="record-columns"><div><span>LEADERSHIP</span><strong>{d.leadership}</strong></div><div><span>DUTIES</span><strong>{d.duties.join(' · ')}</strong></div><div><span>POSITIONS</span><strong>{d.positions}</strong></div></div></div><div className="recruitment"><span className={`status-chip ${d.recruitment.includes('Accepting') ? 'open' : ''}`}><span />{d.recruitment}</span><a href={d.application} className="text-link">APPLICATION <ArrowRight size={13} /></a></div></article>)}</div></PageFrame>; }

export function Ownership() { return <PageFrame kicker="WHO RUNS THE PLACE · 04" title="The staff team" intro="These are the people who handle the work behind the sessions: answering questions, helping departments, sorting problems, and keeping the community moving."><div className="board-header"><div>ADMINISTRATION TEAM</div><div>SPRINGFIELD ROLEPLAY ADMINISTRATION</div><div>SPRINGFIELD COUNTY · 1980</div></div><div className="board-list">{boardMembers.map((m, i) => <article className="board-row" key={m.name}><div className="board-index">0{i + 1}</div><div className="board-seal">♛</div><div className="board-person"><h2>{m.name}</h2><div className="board-position">{m.position}</div></div><div className="board-area"><span>RESPONSIBILITY</span><strong>{m.area}</strong></div><p>{m.bio}</p></article>)}</div></PageFrame>; }

export function Applications() { return <PageFrame kicker="JOIN A DEPARTMENT · 05" title="Department applications" intro="Read the position, check the current status, and apply through Discord. If you are accepted, expect to learn the department before taking a full shift on your own."><div className="application-list">{applications.map((a) => <article className="application-row" key={a.department}><div className="application-icon"><FileText size={19} /></div><div className="application-body"><div className="record-code">{a.department}</div><h2>{a.position}</h2><p>{a.requirements}</p></div><div className="application-action"><span className={`status-chip ${a.status === 'Open' ? 'open' : ''}`}><span />{a.status}</span><a href="https://discord.com" target="_blank" rel="noreferrer" className="button button-small">APPLY <ExternalLink size={13} /></a></div></article>)}</div></PageFrame>; }

export function Status() { return <PageFrame kicker="SERVER DESK · 06" title="Server status" intro="The live server connection is not set up yet. Rather than show a made-up player count, this page tells you exactly what is and is not available."><div className="status-panel"><div className="status-panel-top"><div><div className="eyebrow">RIGHT NOW</div><h2>Live check not connected</h2></div><WifiOff size={28} /></div><div className="status-grid"><div><span>EXPERIENCE</span><strong>Roblox ERLC</strong></div><div><span>AVAILABILITY</span><strong className="status-muted">Waiting for the status feed</strong></div><div><span>PLAYER COUNT</span><strong className="status-muted">Not available</strong></div><div><span>LAST UPDATED</span><strong>Not connected yet</strong></div></div><p className="status-note"><Clock3 size={14} /> Once an official status endpoint is available, it can be connected here.</p></div><div className="status-note-box"><Users size={18} /><p>The rest of the site is still available: read the rules, look through the departments, or join the Discord to ask about the next session.</p><Link href="/about" className="text-link">ABOUT THE COMMUNITY <ArrowRight size={13} /></Link></div></PageFrame>; }

export function Rules() { return <PageFrame kicker="HOUSE RULES · 07" title="Rules for a good session" intro="The rules are simple: respect the people you are playing with, follow the department you joined, and do not ruin a scene for someone else just because you can."><div className="rules-list">{['Do not harass, bait, or target other members.', 'Follow the supervisor and department procedures during a shift.', 'Keep the 1980s setting in mind when it affects the scene.', 'Use common sense, communicate, and let other players have their turn.'].map((rule, i) => <div className="rule-row" key={rule}><span>0{i + 1}</span><p>{rule}</p><Check size={16} /></div>)}</div></PageFrame>; }
